 const actionTypes= {
    ADD_TODO_CATEGORY: 'ADD_TODO_CATEGORY',
    EDIT_TODO_CATEGORY: 'EDIT_TODO_CATEGORY',
    DELETE_TODO_CATEGORY: 'DELETE_TODO_CATEGORY',
    ADD_TODO: 'ADD_TODO',
    EDIT_TODO: 'EDIT_TODO',
    DELETE_TODO: 'DELETE_TODO',
}


export default actionTypes